# Generated by Django 5.2.6 on 2026-07-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Paused'), (4, 'Completed'), (5, 'Cancelled'), (6, 'Transferred'), (7, 'Open'), (8, 'Resolved'), (9, 'Closed'), (10, 'Preparing'), (11, 'Delivered'), (12, 'Skipped'), (13, 'Waiting'), (14, 'Approved'), (15, 'Rejected'), (16, 'Paid'), (17, 'Payment Pending'), (18, 'Payment Received'), (19, 'Payment Failed'), (20, 'Payment Refunded')], default=1)),
                ('adminRemark', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
