# Generated by Django 5.2.6 on 2026-07-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('ondemand', '0002_rename_subowner_ondemandmodel_vendor_and_more'),
        ('onetimeorder', '0002_remove_onetimeordermodel_subowner_and_more'),
        ('order', '0002_alter_ordermodel_delivery_alter_ordermodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryModel',
        ),
    ]
