# Generated by Django 5.2.6 on 2026-07-03 05:44

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTypeModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(choices=[('daily_ghar_ka_khana', 'Daily Ghar Ka Khana Plans'), ('pocket_friendly_meals', 'Pocket Friendly Meals Plans'), ('desi_rice_bowl_combos', 'Desi Rice Bowl Combos Plans'), ('fitness_meals', 'Fitness Meal Plans')], default='daily_ghar_ka_khana', max_length=500)),
                ('plan_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('breakfast_lunch', 'Breakfast + Lunch'), ('breakfast_dinner', 'Breakfast + Dinner'), ('lunch_dinner', 'Lunch + Dinner'), ('breakfast_lunch_dinner', 'Breakfast + Lunch + Dinner')], default='breakfast', max_length=500)),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=3)),
                ('name', models.CharField(default='', max_length=500)),
                ('title', models.CharField(default='', max_length=500)),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='offer.offermodel')),
                ('subOwner', models.ForeignKey(blank=True, limit_choices_to={'userType': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPricingModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_best_offer', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='product.productmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
