# Generated by Django 6.0.6 on 2026-06-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='plan_name',
            field=models.CharField(max_length=500),
        ),
    ]
