# Generated by Django 5.2.6 on 2026-06-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='isSubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
