# Generated by Django 5.2.6 on 2026-07-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='subOwner',
            new_name='vendor',
        ),
    ]
