# Generated by Django 5.2.6 on 2026-06-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productmodel_issubscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='isSubscribed',
        ),
    ]
