# Generated by Django 5.2.6 on 2026-06-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productmodel_issubscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='include',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='plan_name',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='short_description',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.CharField(choices=[('daily_ghar_ka_khana', 'Daily Ghar Ka Khana Plans'), ('pocket_friendly_meals', 'Pocket Friendly Meals Plans'), ('desi_rice_bowl_combos', 'Desi Rice Bowl Combos Plans'), ('fitness_meals', 'Fitness Meal Plans')], default='daily_ghar_ka_khana', max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=3),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='plan_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('breakfast_lunch', 'Breakfast + Lunch'), ('breakfast_dinner', 'Breakfast + Dinner'), ('lunch_dinner', 'Lunch + Dinner'), ('breakfast_lunch_dinner', 'Breakfast + Lunch + Dinner')], default='breakfast', max_length=100),
        ),
    ]
