# Generated by Django 5.2.6 on 2026-06-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_delete_offerproductmodel'),
        ('product', '0004_remove_productmodel_include_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='products', to='offer.offermodel'),
        ),
    ]
