# Generated by Django 5.2.6 on 2026-06-30 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_delete_offerproductmodel'),
        ('product', '0005_productmodel_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='offers',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='offer.offermodel'),
        ),
    ]
