# Generated by Django 5.2.6 on 2026-07-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_productmodel_offers_productmodel_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(choices=[('daily_ghar_ka_khana', 'Daily Ghar Ka Khana Plans'), ('pocket_friendly_meals', 'Pocket Friendly Meals Plans'), ('desi_rice_bowl_combos', 'Desi Rice Bowl Combos Plans'), ('fitness_meals', 'Fitness Meal Plans')], default='daily_ghar_ka_khana', max_length=500),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='plan_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('breakfast_lunch', 'Breakfast + Lunch'), ('breakfast_dinner', 'Breakfast + Dinner'), ('lunch_dinner', 'Lunch + Dinner'), ('breakfast_lunch_dinner', 'Breakfast + Lunch + Dinner')], default='breakfast', max_length=500),
        ),
    ]
