# Generated by Django 5.2.6 on 2026-06-30 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('users', '0003_alter_useraddress_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequestModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('feedback', 'Feedback'), ('complaint', 'Complaint'), ('food_quality', 'Food Quality'), ('delivery_issue', 'Delivery Issue'), ('refund', 'Refund'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
