# Generated by Django 5.2.6 on 2026-07-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orderType', models.IntegerField(choices=[(1, 'Subscription'), (2, 'One Time'), (3, 'On Demand')], default=1)),
                ('orderId', models.PositiveIntegerField(default=0)),
                ('issueType', models.IntegerField(choices=[(1, 'Order'), (2, 'Payment'), (3, 'Delivery'), (4, 'Food Quality'), (5, 'Refund'), (6, 'Other')], default=1)),
                ('description', models.TextField(default='')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Paused'), (4, 'Completed'), (5, 'Cancelled'), (6, 'Transferred'), (7, 'Open'), (8, 'Resolved'), (9, 'Closed'), (10, 'Preparing'), (11, 'Delivered'), (12, 'Skipped'), (13, 'Waiting'), (14, 'Approved'), (15, 'Rejected'), (16, 'Paid'), (17, 'Payment Pending'), (18, 'Payment Received'), (19, 'Payment Failed'), (20, 'Payment Refunded')], default=7)),
                ('adminRemark', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
