# Generated by Django 5.2.6 on 2026-07-07 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetimeorder', '0001_initial'),
        ('order', '0001_initial'),
        ('support', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=150)),
                ('issue_type', models.CharField(max_length=50)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'Resolved'), (4, 'Closed')], default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='users.usermodel')),
                ('one_time_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onetimeorder.onetimeordermodel')),
                ('subOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_tickets', to='users.usermodel')),
                ('subscription_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ordermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportMessageModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='support/')),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticketmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SupportRequestModel',
        ),
    ]
