# Generated by Django 5.2.6 on 2026-07-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequestmodel',
            name='order',
        ),
    ]
