# Generated by Django 5.2.6 on 2026-07-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticketmodel_supportmessagemodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticketmodel',
            old_name='customer',
            new_name='user',
        ),
    ]
