# Generated by Django 6.0.6 on 2026-06-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=10, unique=True)),
                ('userType', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('platform', models.IntegerField(default=1)),
                ('profileImage', models.CharField(blank=True, max_length=500, null=True)),
                ('deviceToken', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('deviceId', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('salt', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
