# Generated by Django 5.2.6 on 2026-06-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('salt', models.CharField(default='', max_length=255)),
                ('phoneNumber', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('userType', models.IntegerField(choices=[(1, 'Owner'), (2, 'Sub Owner'), (3, 'Customer'), (4, 'Delivery')])),
                ('platform', models.IntegerField(default=1)),
                ('profileImage', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deviceToken', models.CharField(blank=True, default='', max_length=500)),
                ('deviceId', models.CharField(blank=True, default='', max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addressType', models.IntegerField(choices=[(1, 'Home'), (2, 'Office'), (3, 'Other')], default=1)),
                ('houseNo', models.CharField(blank=True, max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('isDefault', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=3, limit_choices_to={'userType': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
