# Generated by Django 5.2.6 on 2026-07-07 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('salt', models.CharField(default='', max_length=255)),
                ('phoneNumber', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('userType', models.IntegerField(choices=[(1, 'Owner'), (2, 'Sub Owner'), (3, 'Customer'), (4, 'Delivery')], default=2)),
                ('platform', models.IntegerField(default=1)),
                ('profileImage', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deviceToken', models.CharField(blank=True, default='', max_length=500)),
                ('deviceId', models.CharField(blank=True, default='', max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
