# Generated by Django 5.2.6 on 2026-06-28 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['-isDefault', '-id']},
        ),
    ]
