# Generated by Django 5.2.6 on 2026-07-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userType',
            field=models.IntegerField(choices=[(1, 'Owner'), (2, 'Vendor'), (3, 'Customer'), (4, 'Delivery')], default=3),
        ),
    ]
