# Generated by Django 5.2.6 on 2026-06-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraddress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
