# Generated by Django 5.2.6 on 2026-07-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='phoneNumber',
            field=models.CharField(default='', max_length=10),
        ),
    ]
