# Generated by Django 5.2.6 on 2026-07-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraddress_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phoneNumber',
            field=models.CharField(max_length=10),
        ),
    ]
