# Generated by Django 5.2.6 on 2026-06-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferProductModel',
        ),
    ]
