# Generated by Django 5.2.6 on 2026-07-02 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_delete_offerproductmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferUsageModel',
        ),
    ]
