# Generated by Django 5.2.6 on 2026-07-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnDemandModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itemName', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('deliveryDate', models.DateField()),
                ('mealType', models.CharField(blank=True, max_length=30, null=True)),
                ('expectedAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('finalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='on-demand/')),
                ('note', models.TextField(blank=True, null=True)),
                ('rejectReason', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Paid'), (5, 'Preparing'), (6, 'Delivered'), (7, 'Cancelled')], default=1)),
                ('orderNumber', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.addressmodel')),
                ('subOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_on_demand_orders', to='users.usermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_demand_orders', to='users.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
