# Generated by Django 5.2.6 on 2026-07-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('delivery', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnDemandModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mealType', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='breakfast', max_length=500)),
                ('itemName', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('deliveryDate', models.DateField()),
                ('userAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendorAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('finalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='on-demand/')),
                ('note', models.TextField(blank=True, null=True)),
                ('rejectReason', models.TextField(blank=True, null=True)),
                ('cancelReason', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Paused'), (4, 'Completed'), (5, 'Cancelled'), (6, 'Transferred'), (7, 'Open'), (8, 'Resolved'), (9, 'Closed'), (10, 'Preparing'), (11, 'Delivered'), (12, 'Skipped'), (13, 'Waiting'), (14, 'Approved'), (15, 'Rejected'), (16, 'Paid'), (17, 'Payment Pending'), (18, 'Payment Received'), (19, 'Payment Failed'), (20, 'Payment Refunded')], default=1)),
                ('orderNumber', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.addressmodel')),
                ('delivery', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.deliverymodel')),
                ('subOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_on_demand_orders', to='users.usermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_demand_orders', to='users.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
