# Generated by Django 5.2.6 on 2026-07-13 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondemand', '0001_initial'),
        ('users', '0002_alter_usermodel_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ondemandmodel',
            old_name='subOwner',
            new_name='vendor',
        ),
        migrations.AlterField(
            model_name='ondemandmodel',
            name='delivery',
            field=models.ForeignKey(blank=True, limit_choices_to={'userType': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_on_demand_orders', to='users.usermodel'),
        ),
        migrations.AlterField(
            model_name='ondemandmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_on_demand_orders', to='users.usermodel'),
        ),
    ]
