# Generated by Django 5.2.6 on 2026-07-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondemand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ondemandmodel',
            old_name='expectedAmount',
            new_name='userAmount',
        ),
        migrations.RemoveField(
            model_name='ondemandmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='ondemandmodel',
            name='vendorAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ondemandmodel',
            name='mealType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
