# Generated by Django 5.2.6 on 2026-07-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondemand', '0002_rename_expectedamount_ondemandmodel_useramount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ondemandmodel',
            name='mealType',
        ),
        migrations.AddField(
            model_name='ondemandmodel',
            name='plan_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='breakfast', max_length=500),
        ),
    ]
