# Generated by Django 5.2.6 on 2026-07-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ondemand', '0003_remove_ondemandmodel_mealtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ondemandmodel',
            old_name='plan_type',
            new_name='mealType',
        ),
    ]
