# Generated by Django 5.2.6 on 2026-07-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondemand', '0004_rename_plan_type_ondemandmodel_mealtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ondemandmodel',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Paused'), (4, 'Completed'), (5, 'Cancelled'), (6, 'Transferred')], default=1),
        ),
    ]
