# Generated by Django 5.2.6 on 2026-07-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('product', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Paused'), (4, 'Completed'), (5, 'Cancelled'), (6, 'Transferred'), (7, 'Open'), (8, 'Resolved'), (9, 'Closed'), (10, 'Preparing'), (11, 'Delivered'), (12, 'Skipped'), (13, 'Waiting'), (14, 'Approved'), (15, 'Rejected'), (16, 'Paid'), (17, 'Payment Pending'), (18, 'Payment Received'), (19, 'Payment Failed'), (20, 'Payment Refunded')], default=17)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Paused'), (4, 'Completed'), (5, 'Cancelled'), (6, 'Transferred'), (7, 'Open'), (8, 'Resolved'), (9, 'Closed'), (10, 'Preparing'), (11, 'Delivered'), (12, 'Skipped'), (13, 'Waiting'), (14, 'Approved'), (15, 'Rejected'), (16, 'Paid'), (17, 'Payment Pending'), (18, 'Payment Received'), (19, 'Payment Failed'), (20, 'Payment Refunded')], default=2)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('original_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sub_number', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.addressmodel')),
                ('pricing_options', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productpricingmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPause',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='subscription.subscriptionmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
