# Generated by Django 6.0.6 on 2026-06-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='meal_types',
        ),
    ]
