# Generated by Django 5.2.6 on 2026-06-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
