# Generated by Django 5.2.6 on 2026-07-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='subOwner',
        ),
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='total_days',
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Pause'), (3, 'Completed'), (4, 'Cancelled'), (5, 'Transferred'), (6, 'Process')], default=1),
        ),
    ]
