# Generated by Django 5.2.6 on 2026-06-30 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
        ('subscription', '0002_subscriptionmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.offermodel'),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
