# Generated by Django 5.2.6 on 2026-06-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionmodel_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='offer',
        ),
    ]
