# Generated by Django 5.2.6 on 2026-07-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscriptionmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Received'), (3, 'Failed'), (4, 'Refunded')], default=1),
        ),
    ]
