# Generated by Django 5.2.6 on 2026-06-30 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_remove_subscriptionmodel_offer'),
        ('users', '0003_alter_useraddress_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.useraddress'),
        ),
    ]
