# Generated by Django 5.2.6 on 2026-07-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscriptionmodel_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='is_active',
        ),
    ]
