# Generated by Django 5.2.6 on 2026-07-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscriptionmodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
