# Generated by Django 5.2.6 on 2026-07-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_subscriptionmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='start_date',
            field=models.DateField(),
        ),
    ]
