# Generated by Django 5.2.6 on 2026-07-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('addressType', models.IntegerField(choices=[(1, 'Home'), (2, 'Office'), (3, 'Other')], default=1)),
                ('houseNo', models.CharField(blank=True, max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.PositiveIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('isDefault', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=3, limit_choices_to={'userType': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.usermodel')),
            ],
            options={
                'ordering': ['-isDefault', '-id'],
            },
        ),
    ]
