# Generated by Django 5.2.6 on 2026-06-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('delivery_date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Assigned'), (3, 'Out For Delivery'), (4, 'Delivered'), (5, 'Cancelled'), (6, 'Skipped'), (7, 'Paused')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subOwner', models.ForeignKey(blank=True, limit_choices_to={'userType': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subowner_orders', to='users.usermodel')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='subscription.subscriptionmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
            options={
                'unique_together': {('subscription', 'meal_type', 'delivery_date')},
            },
        ),
    ]
