# Generated by Django 5.2.6 on 2026-07-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='subOwner',
        ),
    ]
