# Generated by Django 5.2.6 on 2026-07-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_ordermodel_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Preparing'), (3, 'Delivered'), (4, 'Cancelled')], default=1),
        ),
    ]
