# Generated by Django 5.2.6 on 2026-07-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Preparing'), (3, 'Delivered'), (4, 'Cancelled'), (5, 'Skipped')], default=1),
        ),
    ]
