# Generated by Django 5.2.6 on 2026-07-03 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '__first__'),
        ('product', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2)),
                ('review', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='order.ordermodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='product.productmodel')),
                ('subOwner', models.ForeignKey(limit_choices_to={'userType': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='subowner_reviews', to='users.usermodel')),
                ('user', models.ForeignKey(limit_choices_to={'userType': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='users.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
