# Generated by Django 5.2.6 on 2026-06-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
