# Generated by Django 5.2.6 on 2026-06-30 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_productmodel_offers_productmodel_offer'),
        ('reviews', '0003_alter_reviewmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='product.productmodel'),
        ),
    ]
