# Generated by Django 5.2.6 on 2026-07-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('delivery', '0001_initial'),
        ('offer', '0001_initial'),
        ('product', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeOrderModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateField()),
                ('meal_type', models.CharField(max_length=20)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Paused'), (4, 'Completed'), (5, 'Cancelled'), (6, 'Transferred'), (7, 'Open'), (8, 'Resolved'), (9, 'Closed'), (10, 'Preparing'), (11, 'Delivered'), (12, 'Skipped'), (13, 'Waiting'), (14, 'Approved'), (15, 'Rejected'), (16, 'Paid'), (17, 'Payment Pending'), (18, 'Payment Received'), (19, 'Payment Failed'), (20, 'Payment Refunded')], default=1)),
                ('rejectReason', models.TextField(blank=True, null=True)),
                ('cancelReason', models.TextField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.addressmodel')),
                ('delivery', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.deliverymodel')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.offermodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productmodel')),
                ('subOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_orders', to='users.usermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
