# Generated by Django 5.2.6 on 2026-07-13 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetimeorder', '0001_initial'),
        ('users', '0002_alter_usermodel_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimeordermodel',
            name='subOwner',
        ),
        migrations.AlterField(
            model_name='onetimeordermodel',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.usermodel'),
        ),
        migrations.AlterField(
            model_name='onetimeordermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_one_time_order', to='users.usermodel'),
        ),
    ]
