# Generated by Django 5.2.6 on 2026-07-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetimeorder', '0002_alter_onetimeordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeordermodel',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Preparing'), (3, 'Delivered'), (4, 'Cancelled'), (5, 'Skip')], default=1),
        ),
    ]
